nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200']  # Autorise explicitement les requêtes venant de localhost:4200
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']  # Autorise les méthodes HTTP pertinentes
        allow_headers: ['Content-Type', 'Authorization', 'origin']  # Autorise les headers
        expose_headers: ['Authorization']  # Expose les headers utiles
        max_age: 3600
    paths:
        '^/api': 
            allow_origin: ['*']  
